//
//  Definitions.h
//  cuaQea
//
//  Created by Enrique Ismael Mendoza Robaina on 01/12/13.
//  Copyright (c) 2013 cuaQea SL. All rights reserved.
//

#import <Foundation/Foundation.h>

FOUNDATION_EXPORT NSString *const URL_API;
FOUNDATION_EXPORT NSString *const URL_API_ESTANQE;
FOUNDATION_EXPORT NSString *const URL_CUAQS_AUDIO;
FOUNDATION_EXPORT NSString *const URL_SHARE_CUAQ;

FOUNDATION_EXPORT NSString *const CELL_TOKEN;

FOUNDATION_EXPORT NSString *const CUAQEA_LOGIN;

FOUNDATION_EXPORT NSString *const USER_ID_LOGGED;
FOUNDATION_EXPORT NSString *const USER_ID;
FOUNDATION_EXPORT NSString *const USER_USERNAME;
FOUNDATION_EXPORT NSString *const USER_MAIL;
FOUNDATION_EXPORT NSString *const USER_PASSWORD;
FOUNDATION_EXPORT NSString *const USER_IMAGE;
FOUNDATION_EXPORT NSString *const USER_IMAGE_IS_LOCAL;
FOUNDATION_EXPORT NSString *const USER_IMAGE_IS_FILE;
FOUNDATION_EXPORT NSString *const USER_VOICENICK;
FOUNDATION_EXPORT NSString *const USER_VOICENICK_DURATION;
FOUNDATION_EXPORT NSString *const USER_DESCRIPTION;
FOUNDATION_EXPORT NSString *const USER_LOCATION;
FOUNDATION_EXPORT NSString *const USER_IS_PREMIUM;

FOUNDATION_EXPORT NSString *const PURCHASE_VOICE_EFFECTS;
FOUNDATION_EXPORT NSString *const PURCHASE_EXTRA_DURATION;

FOUNDATION_EXPORT NSString *const FACEBOOK_REGISTER;
FOUNDATION_EXPORT NSString *const FACEBOOK_TOKEN;
FOUNDATION_EXPORT NSString *const FACEBOOK_PROFILE;
FOUNDATION_EXPORT NSString *const FACEBOOK_MAIL;
FOUNDATION_EXPORT NSString *const FACEBOOK_ID;
FOUNDATION_EXPORT NSString *const FACEBOOK_IMAGE;
FOUNDATION_EXPORT NSString *const FACEBOOK_NAME;
FOUNDATION_EXPORT NSString *const FACEBOOK_USERNAME;
FOUNDATION_EXPORT NSString *const FACEBOOK_LOGGED;
FOUNDATION_EXPORT NSString *const FACEBOOK_LOGGED_BACKEND;
FOUNDATION_EXPORT NSString *const FACEBOOK_DECLINED_PREMISSIONS;

FOUNDATION_EXPORT NSString *const TWITTER_REGISTER;
FOUNDATION_EXPORT NSString *const TWITTER_TOKEN;
FOUNDATION_EXPORT NSString *const TWITTER_SECRET;
FOUNDATION_EXPORT NSString *const TWITTER_PROFILE;
FOUNDATION_EXPORT NSString *const TWITTER_NAME;
FOUNDATION_EXPORT NSString *const TWITTER_USERNAME;
FOUNDATION_EXPORT NSString *const TWITTER_LOCATION;
FOUNDATION_EXPORT NSString *const TWITTER_ID;
FOUNDATION_EXPORT NSString *const TWITTER_MAIL;
FOUNDATION_EXPORT NSString *const TWITTER_IMAGE;
FOUNDATION_EXPORT NSString *const TWITTER_LOGGED;
FOUNDATION_EXPORT NSString *const TWITTER_LOGGED_BACKEND;
FOUNDATION_EXPORT NSString *const TWITTER_ACCOUNT_SESSION;

FOUNDATION_EXPORT NSString *const SHARE_BY_TWITTER;
FOUNDATION_EXPORT NSString *const SHARE_BY_TWITTER_BY_DEFAULT;
FOUNDATION_EXPORT NSString *const SHARE_BY_FACEBOOK;
FOUNDATION_EXPORT NSString *const SHARE_BY_FACEBOOK_BY_DEFAULT;

FOUNDATION_EXPORT NSString *const EMAIL_REPORT;

FOUNDATION_EXPORT NSString *const BACK_VIEWS;

FOUNDATION_EXPORT NSString *const IS_PLAYING;
FOUNDATION_EXPORT NSString *const PLAYING_ID;

FOUNDATION_EXPORT NSString *const CONSUME_RECORD_TIMES;
FOUNDATION_EXPORT NSString *const CONSUME_RECORD_TIMES_SHOWED;

#pragma mark Settings

FOUNDATION_EXPORT NSTimeInterval const ALERT_TIME;
FOUNDATION_EXPORT NSTimeInterval const ALERT_TIME_LONG;
FOUNDATION_EXPORT float const ALERT_ALPHA;
FOUNDATION_EXPORT int const MAX_UPLOAD_SIZE;
FOUNDATION_EXPORT int const MAX_LIST_ELEMENTS;
FOUNDATION_EXPORT int const MAX_USERNAME_LENGHT;
FOUNDATION_EXPORT int const MAX_CUAQ_TITLE_LENGHT;
FOUNDATION_EXPORT int const MAX_RECOMMENDED_PEOPLE;
FOUNDATION_EXPORT int const MORE_PAGE_SIZE;
FOUNDATION_EXPORT int const INITIAL_PAGE_SIZE;
FOUNDATION_EXPORT int const EXTRA_CUAQ_TIME;
FOUNDATION_EXPORT int const MAX_TIMES_TO_REMEMBER_EXTRA_DURATION;
FOUNDATION_EXPORT int const REMEMBER_RECORD_TIME_INTERVAL;

FOUNDATION_EXPORT NSString *const ERROR_TITLE_MSG;
FOUNDATION_EXPORT NSString *const ERROR_NO_ACCOUNTS;
FOUNDATION_EXPORT NSString *const ERROR_PERM_ACCESS;
FOUNDATION_EXPORT NSString *const ERROR_NO_KEYS;
FOUNDATION_EXPORT NSString *const ERROR_OK;

FOUNDATION_EXPORT NSString *const HAS_CHANGED_CUAQS;
FOUNDATION_EXPORT NSString *const HAS_CHANGED_FOLLOWING;

FOUNDATION_EXPORT NSString *const INFO_INVITE_TO_UNLOCK_EFFECTS_SHOWED;
FOUNDATION_EXPORT NSString *const INFO_INVITE_TO_UNLOCK_EFFECTS_SHOWED_ONCE;
FOUNDATION_EXPORT NSString *const INFO_INVITE_TO_EXTRA_DURATION_SHOWED;
FOUNDATION_EXPORT NSString *const HAS_INVITED;
FOUNDATION_EXPORT NSString *const INVITATIONS_NUMBER;
FOUNDATION_EXPORT NSString *const HAS_EFFECTS_FOR_FREE;

#pragma mark -

#pragma mark Images

FOUNDATION_EXPORT NSString *const BACK_BUTTON;
FOUNDATION_EXPORT NSString *const BACK_BUTTON_HOVER;

#pragma mark -

FOUNDATION_EXPORT NSString *const NOTIFICATIONS_COUNT;
FOUNDATION_EXPORT NSString *const NOTIFICATIONS_ARRAY;

#pragma mark Messages

FOUNDATION_EXPORT NSString *const INVITATION_MESSAGE;
FOUNDATION_EXPORT NSString *const INVITATION_MESSAGE_URL;
FOUNDATION_EXPORT NSString *const INVITATION_MESSAGE_IMAGE;
FOUNDATION_EXPORT NSString *const INVITATION_MESSAGE_FULL;

#pragma mark -
#pragma mark Events
FOUNDATION_EXPORT NSString *const EVENT_INVITE_FRIENDS_SUFIX;
FOUNDATION_EXPORT NSString *const EVENT_INVITE_FRIENDS;
FOUNDATION_EXPORT NSString *const EVENT_INVITE_FRIENDS_WHATSAPP;
FOUNDATION_EXPORT NSString *const EVENT_INVITE_FRIENDS_TWITTER;
FOUNDATION_EXPORT NSString *const EVENT_INVITE_FRIENDS_FACEBOOK;


#pragma mark -


@interface Definitions : NSObject

@end
