//
//  CQAAppSettingsDefinitions.h
//  diary
//
//  Created by Enrique Ismael Mendoza Robaina on 17/11/14.
//  Copyright (c) 2014 cuaQea SL. All rights reserved.
//

#import <Foundation/Foundation.h>

FOUNDATION_EXPORT NSString *const FIRST_TIME;
FOUNDATION_EXPORT NSString *const SETTINGS_LOCAL_NOTIFICATIONS;
FOUNDATION_EXPORT NSString *const SETTINGS_LOCAL_NOTIFICATION_DAILY_ACTION_SCHEDULE_DATE;
FOUNDATION_EXPORT NSString *const SETTINGS_SOCIAL_SHARE_BY_TWITTER;
FOUNDATION_EXPORT NSString *const SETTINGS_SOCIAL_SHARE_BY_FACEBOOK;
FOUNDATION_EXPORT NSString *const SETTINGS_USAGE_LAST_APP_LAUNCHING;
FOUNDATION_EXPORT NSString *const SETTINGS_USAGE_LAST_MAIN_ACTION;
FOUNDATION_EXPORT NSString *const SETTINGS_USAGE_;

@interface CQAAppSettingsDefinitions : NSObject

@end
